import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-donor',
  templateUrl: './donor.component.html',
  styleUrls: ['./donor.component.scss']
})
export class DonorComponent implements OnInit {
  form: {
    prefix: string,
    fname: string,
    lname: string,
    czid: string,
    dob: Date,
    sex: string,
    weight: number | null,
    address: string,
    province: number | null,
    district: number | null,
    subdistrict: number | null,
    mobile: string,
    email: string,
    occupation: string,
    old_prefix: string,
    old_fname: string,
    old_lname: string,
  } = {
      prefix: "",
      fname: "",
      lname: "",
      czid: "",
      dob: new Date(),
      sex: "",
      weight: null,
      address: "",
      province: null,
      district: null,
      subdistrict: null,
      mobile: "",
      email: "",
      occupation: "",
      old_prefix: "",
      old_fname: "",
      old_lname: "",
    }
  form2: {
    q_1: boolean | null,
    q_2: boolean | null,
    q_3: boolean | null,
    q_4: boolean | null,
    q_5: boolean | null,
    q_6: boolean | null,
    q_7: boolean | null,
    q_8: boolean | null,
    q_9: boolean | null,
    q_10: boolean | null,
    q_11: boolean | null,
    q_12: boolean | null,
    q_13: boolean | null,
    q_14: boolean | null,
    q_15: boolean | null,
    q_16: boolean | null,
    q_17: boolean | null,
    q_18: boolean | null,
    q_19: boolean | null,
    q_20: boolean | null,
    q_21: boolean | null,
    q_22: boolean | null,
    q_23: boolean | null,
    q_24: boolean | null,
    q_25: boolean | null,
    q_26: boolean | null,
    q_27: boolean | null,
    q_28: boolean | null,
    q_29: boolean | null,
    q_30: boolean | null,
    q_31: boolean | null,
    q_32: boolean | null,
    q_33: boolean | null,
    q_34: boolean | null,
    q_35: boolean | null,
    q_36: boolean | null,
    q_37: boolean | null,
    q_38: boolean | null,
    q_39: boolean | null,
  } = {
      q_1: null,
      q_2: null,
      q_3: null,
      q_4: null,
      q_5: null,
      q_6: null,
      q_7: null,
      q_8: null,
      q_9: null,
      q_10: null,
      q_11: null,
      q_12: null,
      q_13: null,
      q_14: null,
      q_15: null,
      q_16: null,
      q_17: null,
      q_18: null,
      q_19: null,
      q_20: null,
      q_21: null,
      q_22: null,
      q_23: null,
      q_24: null,
      q_25: null,
      q_26: null,
      q_27: null,
      q_28: null,
      q_29: null,
      q_30: null,
      q_31: null,
      q_32: null,
      q_33: null,
      q_34: null,
      q_35: null,
      q_36: null,
      q_37: null,
      q_38: null,
      q_39: null,
    }
  constructor() { }

  ngOnInit(): void {
  }


}
